### ISSUE TITLE
Spark Todo List

### ISSUE THREAD

**Issue by seshurajup** [seshurajup/myNoteBooks#1]
- [ ] Scala Basics
  - [ ] Spark core concepts
  - [ ] RDD
  - [ ] Accumulators
  - [ ] Broadcast Var
  - [ ] Data Frames
  - [ ] Data Sets
  - [ ] Sql
- [ ] Machine Learning
  - [ ] Basics
  - [ ] Pipeline
  - [ ] Pre-Processing
  - [ ] Regression
  - [ ] Classification
  - [ ] Clustering
  - [ ] Collaborative filtering
  - [ ] Frequent pattern mining
  - [ ] Model selection & tunning
  - [ ] Advanced topics
  - [ ] Data types
  - [ ] Basic Statistics
  - [ ] Dimension Reduction
  - [ ] Evaluation metrics
  - [ ] PMML model export
- [ ] Structure Streaming Basics
  - [ ] Part 1
  - [ ] Part 2
  - [ ] Part 3
- [ ] Spark Streaming
  - [ ] Basic concepts part 1
  - [ ] Basic concepts part 2
  - [ ] Performance tuning
- [ ] Graphx
  - [ ] Basics
  - [ ] Algorithms
